name: Release workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  GHR_PROJECT_REPONAME: ui5-language-assistant
  GHR_PROJECT_USERNAME: SAP

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # will fetch all history
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
        with:
          args: --include-submodules lint

  version:
    # Run version job only on pushes to the main branch. The job depends on completion of the build job.
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    runs-on: ${{ matrix.os }}

    needs: [build, compliance]
    outputs:
      changes: ${{ steps.changesetVersion.outputs.changes }} # map step output to job output

    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_PAT }} # needed to auto trigger release job

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

